//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helix.App.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your new password.
        /// </summary>
        internal static string AddConfirmNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddConfirmNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password.
        /// </summary>
        internal static string AddCurrentPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddCurrentPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Drive.
        /// </summary>
        internal static string AddDrive {
            get {
                return ResourceManager.GetString("AddDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your drive&apos;s name.
        /// </summary>
        internal static string AddDriveNamePlaceholder {
            get {
                return ResourceManager.GetString("AddDriveNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or hostname.
        /// </summary>
        internal static string AddNasHostPlaceholder {
            get {
                return ResourceManager.GetString("AddNasHostPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your NAS&apos; password.
        /// </summary>
        internal static string AddNasPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddNasPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your NAS&apos; username.
        /// </summary>
        internal static string AddNasUsernamePlaceholder {
            get {
                return ResourceManager.GetString("AddNasUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add network&apos;s drive letter.
        /// </summary>
        internal static string AddNetworkDriveLetterPlaceholder {
            get {
                return ResourceManager.GetString("AddNetworkDriveLetterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password.
        /// </summary>
        internal static string AddNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new username.
        /// </summary>
        internal static string AddNewUsernamePlaceholder {
            get {
                return ResourceManager.GetString("AddNewUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditlogs.
        /// </summary>
        internal static string Auditlogs {
            get {
                return ResourceManager.GetString("Auditlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect your drives as soon as Helix opens..
        /// </summary>
        internal static string AutoConnectDescription {
            get {
                return ResourceManager.GetString("AutoConnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto connect drives on launch.
        /// </summary>
        internal static string AutoConnectDrivesOnLaunch {
            get {
                return ResourceManager.GetString("AutoConnectDrivesOnLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto minimize app.
        /// </summary>
        internal static string AutoMinimizeApp {
            get {
                return ResourceManager.GetString("AutoMinimizeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Helix to the taskbar once the timer runs out..
        /// </summary>
        internal static string AutoMinimizeDescription {
            get {
                return ResourceManager.GetString("AutoMinimizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account info..
        /// </summary>
        internal static string ChangeYourAccountInfo {
            get {
                return ResourceManager.GetString("ChangeYourAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new password.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        internal static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Drive.
        /// </summary>
        internal static string DeleteDrive {
            get {
                return ResourceManager.GetString("DeleteDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive&apos;s name.
        /// </summary>
        internal static string DriveName {
            get {
                return ResourceManager.GetString("DriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Drives.
        /// </summary>
        internal static string ExportDrives {
            get {
                return ResourceManager.GetString("ExportDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Drives.
        /// </summary>
        internal static string ImportDrives {
            get {
                return ResourceManager.GetString("ImportDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language used across the app..
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your preferences..
        /// </summary>
        internal static string ManageYourPreferences {
            get {
                return ResourceManager.GetString("ManageYourPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS address.
        /// </summary>
        internal static string NasHost {
            get {
                return ResourceManager.GetString("NasHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS manager.
        /// </summary>
        internal static string NasManager {
            get {
                return ResourceManager.GetString("NasManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS Password.
        /// </summary>
        internal static string NasPassword {
            get {
                return ResourceManager.GetString("NasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS Username.
        /// </summary>
        internal static string NasUsername {
            get {
                return ResourceManager.GetString("NasUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions you take in Helix will appear here..
        /// </summary>
        internal static string NoAuditlogsMessage {
            get {
                return ResourceManager.GetString("NoAuditlogsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing logged yet.
        /// </summary>
        internal static string NoAuditlogsTitle {
            get {
                return ResourceManager.GetString("NoAuditlogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first network drive to reach your NAS in a single click..
        /// </summary>
        internal static string NoDrivesMessage {
            get {
                return ResourceManager.GetString("NoDrivesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drives yet.
        /// </summary>
        internal static string NoDrivesTitle {
            get {
                return ResourceManager.GetString("NoDrivesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press CTRL + ENTER.
        /// </summary>
        internal static string PressCtrlEnter {
            get {
                return ResourceManager.GetString("PressCtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to Helix!.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the log.
        /// </summary>
        internal static string SearchAuditlogs {
            get {
                return ResourceManager.GetString("SearchAuditlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search drives.
        /// </summary>
        internal static string SearchDrives {
            get {
                return ResourceManager.GetString("SearchDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set desktop shortcut.
        /// </summary>
        internal static string SetDesktopShortcut {
            get {
                return ResourceManager.GetString("SetDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep a Helix shortcut on your desktop..
        /// </summary>
        internal static string SetDesktopShortcutDescription {
            get {
                return ResourceManager.GetString("SetDesktopShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set on startup.
        /// </summary>
        internal static string SetOnStartup {
            get {
                return ResourceManager.GetString("SetOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Helix when you sign in to Windows..
        /// </summary>
        internal static string SetOnStartupDescription {
            get {
                return ResourceManager.GetString("SetOnStartupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show credentials.
        /// </summary>
        internal static string ShowCredentials {
            get {
                return ResourceManager.GetString("ShowCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in.
        /// </summary>
        internal static string SignedIn {
            get {
                return ResourceManager.GetString("SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Usage.
        /// </summary>
        internal static string StorageUsage {
            get {
                return ResourceManager.GetString("StorageUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time before minimize.
        /// </summary>
        internal static string TimeBeforeMinimize {
            get {
                return ResourceManager.GetString("TimeBeforeMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds to wait before minimising..
        /// </summary>
        internal static string TimerCountDescription {
            get {
                return ResourceManager.GetString("TimerCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer count in seconds.
        /// </summary>
        internal static string TimerCountInSeconds {
            get {
                return ResourceManager.GetString("TimerCountInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Connected Drives.
        /// </summary>
        internal static string TotalConnectedDrives {
            get {
                return ResourceManager.GetString("TotalConnectedDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Storage of NAS.
        /// </summary>
        internal static string TotalStorageOfNas {
            get {
                return ResourceManager.GetString("TotalStorageOfNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Drive.
        /// </summary>
        internal static string UpdateDrive {
            get {
                return ResourceManager.GetString("UpdateDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your password.
        /// </summary>
        internal static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your username.
        /// </summary>
        internal static string UpdateYourUsername {
            get {
                return ResourceManager.GetString("UpdateYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        internal static string UsernameField {
            get {
                return ResourceManager.GetString("UsernameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back to Helix!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your auditlogs.
        /// </summary>
        internal static string YourAuditlogs {
            get {
                return ResourceManager.GetString("YourAuditlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password.
        /// </summary>
        internal static string YourCurrentPassword {
            get {
                return ResourceManager.GetString("YourCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your drives.
        /// </summary>
        internal static string YourDrives {
            get {
                return ResourceManager.GetString("YourDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password.
        /// </summary>
        internal static string YourNewPassword {
            get {
                return ResourceManager.GetString("YourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sort order.
        /// </summary>
        internal static string YourSortOrder {
            get {
                return ResourceManager.GetString("YourSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username.
        /// </summary>
        internal static string YourUsername {
            get {
                return ResourceManager.GetString("YourUsername", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Connect automatically.
        /// </summary>
        internal static string AutoConnectDrive {
            get {
                return ResourceManager.GetString("AutoConnectDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection works.
        /// </summary>
        internal static string ConnectionTestSucceeded {
            get {
                return ResourceManager.GetString("ConnectionTestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect at Windows sign-in.
        /// </summary>
        internal static string PersistentMapping {
            get {
                return ResourceManager.GetString("PersistentMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect using the server name.
        /// </summary>
        internal static string ConnectByHostname {
            get {
                return ResourceManager.GetString("ConnectByHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect all drives.
        /// </summary>
        internal static string TrayConnectAll {
            get {
                return ResourceManager.GetString("TrayConnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect all drives.
        /// </summary>
        internal static string TrayDisconnectAll {
            get {
                return ResourceManager.GetString("TrayDisconnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive disconnected.
        /// </summary>
        internal static string TrayDriveDisconnected {
            get {
                return ResourceManager.GetString("TrayDriveDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive reconnected.
        /// </summary>
        internal static string TrayDriveReconnected {
            get {
                return ResourceManager.GetString("TrayDriveReconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Helix.
        /// </summary>
        internal static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Helix.
        /// </summary>
        internal static string TrayOpen {
            get {
                return ResourceManager.GetString("TrayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helix is still running in the notification area.
        /// </summary>
        internal static string TrayStillRunning {
            get {
                return ResourceManager.GetString("TrayStillRunning", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to {0} was added.
        /// </summary>
        internal static string AuditDriveCreated {
            get {
                return ResourceManager.GetString("AuditDriveCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was removed.
        /// </summary>
        internal static string AuditDriveDeleted {
            get {
                return ResourceManager.GetString("AuditDriveDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lost its connection.
        /// </summary>
        internal static string AuditDriveDisconnected {
            get {
                return ResourceManager.GetString("AuditDriveDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be reconnected: {1}.
        /// </summary>
        internal static string AuditDriveReconnectFailed {
            get {
                return ResourceManager.GetString("AuditDriveReconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was reconnected automatically.
        /// </summary>
        internal static string AuditDriveReconnected {
            get {
                return ResourceManager.GetString("AuditDriveReconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was changed.
        /// </summary>
        internal static string AuditDriveUpdated {
            get {
                return ResourceManager.GetString("AuditDriveUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low space warning.
        /// </summary>
        internal static string StorageAlertThreshold {
            get {
                return ResourceManager.GetString("StorageAlertThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me when a volume has less than this percentage of free space left. 0 turns the warning off..
        /// </summary>
        internal static string StorageAlertThresholdDescription {
            get {
                return ResourceManager.GetString("StorageAlertThresholdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage is running low.
        /// </summary>
        internal static string TrayStorageLow {
            get {
                return ResourceManager.GetString("TrayStorageLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1}% free space left..
        /// </summary>
        internal static string TrayStorageLowMessage {
            get {
                return ResourceManager.GetString("TrayStorageLowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete '{0}'? The drives in it are not affected..
        /// </summary>
        internal static string DeleteGroupConfirm {
            get {
                return ResourceManager.GetString("DeleteGroupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect {0}.
        /// </summary>
        internal static string TrayConnectGroup {
            get {
                return ResourceManager.GetString("TrayConnectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install.
        /// </summary>
        internal static string UpdateInstall {
            get {
                return ResourceManager.GetString("UpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading… {0}%.
        /// </summary>
        internal static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install.
        /// </summary>
        internal static string UpdateReady {
            get {
                return ResourceManager.GetString("UpdateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helix {0} has been downloaded..
        /// </summary>
        internal static string UpdateReadyMessage {
            get {
                return ResourceManager.GetString("UpdateReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install and restart.
        /// </summary>
        internal static string UpdateInstallNow {
            get {
                return ResourceManager.GetString("UpdateInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password was not right..
        /// </summary>
        internal static string LockWrongPassword {
            get {
                return ResourceManager.GetString("LockWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log retention.
        /// </summary>
        internal static string AuditlogRetention {
            get {
                return ResourceManager.GetString("AuditlogRetention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of history to keep. 0 keeps every entry.
        /// </summary>
        internal static string AuditlogRetentionDescription {
            get {
                return ResourceManager.GetString("AuditlogRetentionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logs were saved to:.
        /// </summary>
        internal static string DiagnosticsExported {
            get {
                return ResourceManager.GetString("DiagnosticsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic logs.
        /// </summary>
        internal static string ExportDiagnostics {
            get {
                return ResourceManager.GetString("ExportDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Helix's log files to a folder, to attach to a bug report.
        /// </summary>
        internal static string ExportDiagnosticsDescription {
            get {
                return ResourceManager.GetString("ExportDiagnosticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last connected {0}.
        /// </summary>
        internal static string LastConnectedAt {
            get {
                return ResourceManager.GetString("LastConnectedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never connected.
        /// </summary>
        internal static string NeverConnected {
            get {
                return ResourceManager.GetString("NeverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open release page.
        /// </summary>
        internal static string OpenReleasePage {
            get {
                return ResourceManager.GetString("OpenReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version ({0}).
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helix {0} is available. You are running {1}.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check GitHub for a newer release of Helix.
        /// </summary>
        internal static string UpdatesDescription {
            get {
                return ResourceManager.GetString("UpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to the system tray.
        /// </summary>
        internal static string CloseToTray {
            get {
                return ResourceManager.GetString("CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Helix running in the tray when you close the window. Off quits Helix, and nothing reconnects your drives until you open it again..
        /// </summary>
        internal static string CloseToTrayDescription {
            get {
                return ResourceManager.GetString("CloseToTrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify when hidden to the tray.
        /// </summary>
        internal static string NotifyOnMinimizeToTray {
            get {
                return ResourceManager.GetString("NotifyOnMinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification the first time Helix hides itself in the tray each session..
        /// </summary>
        internal static string NotifyOnMinimizeToTrayDescription {
            get {
                return ResourceManager.GetString("NotifyOnMinimizeToTrayDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Connecting….
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting….
        /// </summary>
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your drives have been exported..
        /// </summary>
        internal static string DrivesExported {
            get {
                return ResourceManager.GetString("DrivesExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your drives have been imported..
        /// </summary>
        internal static string DrivesImported {
            get {
                return ResourceManager.GetString("DrivesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated..
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username has been updated..
        /// </summary>
        internal static string UsernameUpdated {
            get {
                return ResourceManager.GetString("UsernameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt export.
        /// </summary>
        internal static string EncryptExport {
            get {
                return ResourceManager.GetString("EncryptExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a passphrase to protect this drive export..
        /// </summary>
        internal static string EncryptExportMessage {
            get {
                return ResourceManager.GetString("EncryptExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter the same passphrase to confirm..
        /// </summary>
        internal static string EncryptExportConfirmMessage {
            get {
                return ResourceManager.GetString("EncryptExportConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        internal static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm passphrase.
        /// </summary>
        internal static string ConfirmPassphrase {
            get {
                return ResourceManager.GetString("ConfirmPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrases don't match.
        /// </summary>
        internal static string PassphrasesDontMatch {
            get {
                return ResourceManager.GetString("PassphrasesDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two passphrases you entered are different. Please try again..
        /// </summary>
        internal static string PassphrasesDontMatchMessage {
            get {
                return ResourceManager.GetString("PassphrasesDontMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt import.
        /// </summary>
        internal static string DecryptImport {
            get {
                return ResourceManager.GetString("DecryptImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the passphrase used when this vault was exported..
        /// </summary>
        internal static string DecryptImportMessage {
            get {
                return ResourceManager.GetString("DecryptImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable.
        /// </summary>
        internal static string StatusUnreachable {
            get {
                return ResourceManager.GetString("StatusUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: connected — the mount finished after the timeout..
        /// </summary>
        internal static string DriveConnectedLate {
            get {
                return ResourceManager.GetString("DriveConnectedLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NAS is not on this network. Helix keeps trying..
        /// </summary>
        internal static string StatusUnreachableHint {
            get {
                return ResourceManager.GetString("StatusUnreachableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in file manager.
        /// </summary>
        internal static string OpenInFileManager {
            get {
                return ResourceManager.GetString("OpenInFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string UnitSeconds {
            get {
                return ResourceManager.GetString("UnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string UnitMinutes {
            get {
                return ResourceManager.GetString("UnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string UnitDays {
            get {
                return ResourceManager.GetString("UnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string UnitPercent {
            get {
                return ResourceManager.GetString("UnitPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep everything.
        /// </summary>
        internal static string RetentionKeepEverything {
            get {
                return ResourceManager.GetString("RetentionKeepEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string StorageAlertOff {
            get {
                return ResourceManager.GetString("StorageAlertOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string IdleLockNever {
            get {
                return ResourceManager.GetString("IdleLockNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect all.
        /// </summary>
        internal static string ConnectAll {
            get {
                return ResourceManager.GetString("ConnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect all.
        /// </summary>
        internal static string DisconnectAll {
            get {
                return ResourceManager.GetString("DisconnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        internal static string DrivesSelected {
            get {
                return ResourceManager.GetString("DrivesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect drives.
        /// </summary>
        internal static string DisconnectConfirmTitle {
            get {
                return ResourceManager.GetString("DisconnectConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drive will be unmounted. Anything you have open on it may fail to save..
        /// </summary>
        internal static string DisconnectConfirmOne {
            get {
                return ResourceManager.GetString("DisconnectConfirmOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} drives will be unmounted. Anything you have open on them may fail to save..
        /// </summary>
        internal static string DisconnectConfirmMany {
            get {
                return ResourceManager.GetString("DisconnectConfirmMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        internal static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drives match.
        /// </summary>
        internal static string NoDrivesMatchTitle {
            get {
                return ResourceManager.GetString("NoDrivesMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here matches what you typed. Clear the search to see every drive again..
        /// </summary>
        internal static string NoDrivesMatchMessage {
            get {
                return ResourceManager.GetString("NoDrivesMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries match.
        /// </summary>
        internal static string NoAuditlogsMatchTitle {
            get {
                return ResourceManager.GetString("NoAuditlogsMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing in the log matches what you typed. Clear the search to see the whole history again..
        /// </summary>
        internal static string NoAuditlogsMatchMessage {
            get {
                return ResourceManager.GetString("NoAuditlogsMatchMessage", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete '{0}'?.
        /// </summary>
        internal static string DeleteDriveConfirm {
            get {
                return ResourceManager.GetString("DeleteDriveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this drive?.
        /// </summary>
        internal static string DeleteDriveConfirmGeneric {
            get {
                return ResourceManager.GetString("DeleteDriveConfirmGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive not ready.
        /// </summary>
        internal static string DriveNotReady {
            get {
                return ResourceManager.GetString("DriveNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid drive letter.
        /// </summary>
        internal static string InvalidDriveLetter {
            get {
                return ResourceManager.GetString("InvalidDriveLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TB used of {1} TB.
        /// </summary>
        internal static string StorageUsedOf {
            get {
                return ResourceManager.GetString("StorageUsedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose.
        /// </summary>
        internal static string DiagnoseDrive {
            get {
                return ResourceManager.GetString("DiagnoseDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection check.
        /// </summary>
        internal static string DiagnoseTitle {
            get {
                return ResourceManager.GetString("DiagnoseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1}.
        /// </summary>
        internal static string DiagnoseSubtitle {
            get {
                return ResourceManager.GetString("DiagnoseSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking….
        /// </summary>
        internal static string DiagnoseRunning {
            get {
                return ResourceManager.GetString("DiagnoseRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is standing in this drive's way..
        /// </summary>
        internal static string DiagnoseHealthy {
            get {
                return ResourceManager.GetString("DiagnoseHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is what is stopping the drive from connecting..
        /// </summary>
        internal static string DiagnoseProblem {
            get {
                return ResourceManager.GetString("DiagnoseProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check again.
        /// </summary>
        internal static string DiagnoseRunAgain {
            get {
                return ResourceManager.GetString("DiagnoseRunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string DiagnoseStepHostResolution {
            get {
                return ResourceManager.GetString("DiagnoseStepHostResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaching the server.
        /// </summary>
        internal static string DiagnoseStepHostReachable {
            get {
                return ResourceManager.GetString("DiagnoseStepHostReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share and credentials.
        /// </summary>
        internal static string DiagnoseStepShareAndCredentials {
            get {
                return ResourceManager.GetString("DiagnoseStepShareAndCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive letter.
        /// </summary>
        internal static string DiagnoseStepLetterAvailable {
            get {
                return ResourceManager.GetString("DiagnoseStepLetterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not checked, because the server did not answer..
        /// </summary>
        internal static string DiagnoseSkipped {
            get {
                return ResourceManager.GetString("DiagnoseSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server also answers to '{0}'..
        /// </summary>
        internal static string DiagnoseHostSpellingResolved {
            get {
                return ResourceManager.GetString("DiagnoseHostSpellingResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other name for this server could be looked up. Helix will use the address as you typed it..
        /// </summary>
        internal static string DiagnoseHostSpellingUnknown {
            get {
                return ResourceManager.GetString("DiagnoseHostSpellingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server answered on SMB port {0}..
        /// </summary>
        internal static string DiagnosePortOpen {
            get {
                return ResourceManager.GetString("DiagnosePortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to '{0}' did not answer on port 445 or 139. It is switched off, asleep, or on another network..
        /// </summary>
        internal static string DiagnoseHostSilent {
            get {
                return ResourceManager.GetString("DiagnoseHostSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This share is already mounted, so it was not tested again..
        /// </summary>
        internal static string DiagnoseAlreadyMounted {
            get {
                return ResourceManager.GetString("DiagnoseAlreadyMounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The share exists and the stored credentials were accepted..
        /// </summary>
        internal static string DiagnoseCredentialsAccepted {
            get {
                return ResourceManager.GetString("DiagnoseCredentialsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The share answered, but another drive is already signed in to '{0}'. That session is reused, so the stored password was not actually checked..
        /// </summary>
        internal static string DiagnoseCredentialsUntested {
            get {
                return ResourceManager.GetString("DiagnoseCredentialsUntested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server is already signed in under different credentials and that session could not be cleared. Disconnect every drive and Explorer window using it, then try again..
        /// </summary>
        internal static string DiagnoseSessionConflict {
            get {
                return ResourceManager.GetString("DiagnoseSessionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to '{0}' is free..
        /// </summary>
        internal static string DiagnoseLetterFree {
            get {
                return ResourceManager.GetString("DiagnoseLetterFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to '{0}' is already mounted from this share..
        /// </summary>
        internal static string DiagnoseLetterHeldByThisShare {
            get {
                return ResourceManager.GetString("DiagnoseLetterHeldByThisShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to '{0}' is in use by something else on this computer. Choose a free letter..
        /// </summary>
        internal static string DiagnoseLetterHeldByAnother {
            get {
                return ResourceManager.GetString("DiagnoseLetterHeldByAnother", resourceCulture);
            }
        }
    }
}
