//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helix.App.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your new password.
        /// </summary>
        internal static string AddConfirmNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddConfirmNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password.
        /// </summary>
        internal static string AddCurrentPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddCurrentPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Drive.
        /// </summary>
        internal static string AddDrive {
            get {
                return ResourceManager.GetString("AddDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your drive&apos;s name.
        /// </summary>
        internal static string AddDriveNamePlaceholder {
            get {
                return ResourceManager.GetString("AddDriveNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your NAS&apos; IP Address.
        /// </summary>
        internal static string AddNasIpAddressPlaceholder {
            get {
                return ResourceManager.GetString("AddNasIpAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your NAS&apos; password.
        /// </summary>
        internal static string AddNasPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddNasPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your NAS&apos; username.
        /// </summary>
        internal static string AddNasUsernamePlaceholder {
            get {
                return ResourceManager.GetString("AddNasUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add network&apos;s drive letter.
        /// </summary>
        internal static string AddNetworkDriveLetterPlaceholder {
            get {
                return ResourceManager.GetString("AddNetworkDriveLetterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password.
        /// </summary>
        internal static string AddNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("AddNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new username.
        /// </summary>
        internal static string AddNewUsernamePlaceholder {
            get {
                return ResourceManager.GetString("AddNewUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditlogs.
        /// </summary>
        internal static string Auditlogs {
            get {
                return ResourceManager.GetString("Auditlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto connect drives on launch.
        /// </summary>
        internal static string AutoConnectDrivesOnLaunch {
            get {
                return ResourceManager.GetString("AutoConnectDrivesOnLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto minimize app.
        /// </summary>
        internal static string AutoMinimizeApp {
            get {
                return ResourceManager.GetString("AutoMinimizeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account info..
        /// </summary>
        internal static string ChangeYourAccountInfo {
            get {
                return ResourceManager.GetString("ChangeYourAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new password.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        internal static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Drive.
        /// </summary>
        internal static string DeleteDrive {
            get {
                return ResourceManager.GetString("DeleteDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive&apos;s name.
        /// </summary>
        internal static string DriveName {
            get {
                return ResourceManager.GetString("DriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Drives.
        /// </summary>
        internal static string ExportDrives {
            get {
                return ResourceManager.GetString("ExportDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File
        ///.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Drives.
        /// </summary>
        internal static string ImportDrives {
            get {
                return ResourceManager.GetString("ImportDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your preferences..
        /// </summary>
        internal static string ManageYourPreferences {
            get {
                return ResourceManager.GetString("ManageYourPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS IP Address.
        /// </summary>
        internal static string NasIpAddress {
            get {
                return ResourceManager.GetString("NasIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS Password.
        /// </summary>
        internal static string NasPassword {
            get {
                return ResourceManager.GetString("NasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS Username.
        /// </summary>
        internal static string NasUsername {
            get {
                return ResourceManager.GetString("NasUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to Helix!.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search auditlogs.
        /// </summary>
        internal static string SearchAuditlogs {
            get {
                return ResourceManager.GetString("SearchAuditlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Drives.
        /// </summary>
        internal static string SearchDrives {
            get {
                return ResourceManager.GetString("SearchDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your search term (optional).
        /// </summary>
        internal static string SearchTermPlaceholder {
            get {
                return ResourceManager.GetString("SearchTermPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set on startup.
        /// </summary>
        internal static string SetOnStartup {
            get {
                return ResourceManager.GetString("SetOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Usage.
        /// </summary>
        internal static string StorageUsage {
            get {
                return ResourceManager.GetString("StorageUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time before minimize.
        /// </summary>
        internal static string TimeBeforeMinimize {
            get {
                return ResourceManager.GetString("TimeBeforeMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer count in seconds.
        /// </summary>
        internal static string TimerCountInSeconds {
            get {
                return ResourceManager.GetString("TimerCountInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Connect.
        /// </summary>
        internal static string ToggleConnect {
            get {
                return ResourceManager.GetString("ToggleConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Connected Drives.
        /// </summary>
        internal static string TotalConnectedDrives {
            get {
                return ResourceManager.GetString("TotalConnectedDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Storage of NAS.
        /// </summary>
        internal static string TotalStorageOfNas {
            get {
                return ResourceManager.GetString("TotalStorageOfNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Drive.
        /// </summary>
        internal static string UpdateDrive {
            get {
                return ResourceManager.GetString("UpdateDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your password.
        /// </summary>
        internal static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your username.
        /// </summary>
        internal static string UpdateYourUsername {
            get {
                return ResourceManager.GetString("UpdateYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        internal static string UsernameField {
            get {
                return ResourceManager.GetString("UsernameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back to Helix!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your auditlogs.
        /// </summary>
        internal static string YourAuditlogs {
            get {
                return ResourceManager.GetString("YourAuditlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password.
        /// </summary>
        internal static string YourCurrentPassword {
            get {
                return ResourceManager.GetString("YourCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your drives.
        /// </summary>
        internal static string YourDrives {
            get {
                return ResourceManager.GetString("YourDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password.
        /// </summary>
        internal static string YourNewPassword {
            get {
                return ResourceManager.GetString("YourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sort order.
        /// </summary>
        internal static string YourSortOrder {
            get {
                return ResourceManager.GetString("YourSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username.
        /// </summary>
        internal static string YourUsername {
            get {
                return ResourceManager.GetString("YourUsername", resourceCulture);
            }
        }
    }
}
