<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WarningsAsErrors>CS4014</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Maui.Controls" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Helix.Domain\Helix.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Application.UnitTests" />
	</ItemGroup>

</Project>
