<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<WarningsAsErrors>CS4014</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Helix.Domain\Helix.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Application.UnitTests" />
	</ItemGroup>

</Project>
